apiVersion: v1
kind: Secret
metadata:
  name: messages-auth
  labels:
    app.kubernetes.io/component: messages-auth
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  jwt_secret: {{ .Values.messagesJwtSecret | b64enc }}