apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages
  labels:
    {{- include "messages.labels" . | nindent 4}}
    app.kubernetes.io/component: messages
spec:
  replicas: {{ .Values.messages.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: messages
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: messages
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: messages
          image: {{ .Values.messages.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: messages_db_url
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: nodeenv
                  key: messages_node_env
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000