apiVersion: v1
kind: Secret
metadata:
  name: messages-extapis
  labels:
    app.kubernetes.io/component: messages-extapis
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  deepl_key: {{ .Values.messagesDeeplKey | b64enc }}