apiVersion: v1
kind: Secret
metadata:
  name: messages-hosts
  labels:
    app.kubernetes.io/component: messages-hosts
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  support_host: {{ .Values.messagesSupportHost | b64enc }}