apiVersion: v1
kind: Secret
metadata:
  name: hosts
  labels:
    app.kubernetes.io/component: hosts
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  songs_host: {{ .Values.songsHost | b64enc }}
  support_host: {{ .Values.supportHost | b64enc }}
  users_host: {{ .Values.usersHost | b64enc }}