apiVersion: v1
kind: Secret
metadata:
  name: messages_mongodb
  labels:
    app.kubernetes.io/component: messages_mongodb
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  messages_db_url: {{ .Values.messagesMongoUrl | b64enc }}