apiVersion: v1
kind: Secret
metadata:
  name: messages_nodeenv
  labels:
    app.kubernetes.io/component: messages_nodeenv
    {{- include "messages.labels" . | nindent 4}}
type: Opaque
data:
  messages_node_env: {{ .Values.messagesNodeEnv | b64enc }}